version: 0.2

env:
  variables:
    S3_BUCKET: "aserputko-frontendmentor-todo-web"
    CLOUDFRONT_DISTRIBUTION_ID: "E2LZRHO53SZ4RG"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm ci

  pre_build:
    commands:
      - echo Running linting...
      - npm run lint
      - echo Running tests...
      - npm run test

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Build completed
      # - echo Deploying to S3...
      # - aws s3 sync ./dist s3://$S3_BUCKET/ --delete --cache-control "public, max-age=300"
      # - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      # - echo Deployment completed successfully

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: frontend-build-$(date +%Y-%m-%d)

cache:
  paths:
    - node_modules/**/*