version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Running linting...
      - npm run lint
      - echo Running tests...
      - npm run test

  build:
    commands:
      - echo Building the project...
      - npm run build

  post_build:
    commands:
      - echo Build completed
      - echo Deploying to S3...
      - aws s3 sync ./dist s3://aserputko-frontendmentor-todo-web --delete
      - |
        aws s3 sync ./dist s3://aserputko-frontendmentor-todo-web \
          --cache-control "public, max-age=31536000" \
          --exclude "*.html" \
          --exclude "service-worker.js"
      - |
        aws s3 sync ./dist s3://aserputko-frontendmentor-todo-web \
          --cache-control "public, max-age=0, must-revalidate" \
          --include "*.html" \
          --include "service-worker.js"
      - echo Deployment completed successfully

artifacts:
  files:
    - '**/*'
  base-directory: dist
  name: frontend-build-$(date +%Y-%m-%d)

cache:
  paths:
    - node_modules/**/*