version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - npm ci

  pre_build:
    commands:
      - echo Running linting...
      - echo npm run lint
      - npm run lint
      - echo Running tests...
      - echo npm run test
      - npm run test

  build:
    commands:
      - echo Building the project...
      - echo npm run build
      - npm run build
      

  post_build:
    commands:
      - echo Build completed


artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - node_modules/**/*